const crypto=require("crypto");const bcrypt=require("bcrypt");const jwt=require("jsonwebtoken");const Utilisateur=require("../models/Utilisateur");const DUREE_DE_VIE_JETON="24h";
const creerJeton=(u)=>jwt.sign({id:u._id,role:u.role},process.env.JWT_SECRET,{expiresIn:DUREE_DE_VIE_JETON});
async function inscription(req,res){const nom=String(req.body.nom||"").trim();const courriel=String(req.body.courriel||"").trim().toLowerCase();const motDePasse=String(req.body.motDePasse||"");if(nom.length<2||!/^\S+@\S+\.\S+$/.test(courriel)||motDePasse.length<8)return res.status(400).json({message:"Nom, courriel valide et mot de passe de 8 caractères requis"});if(await Utilisateur.exists({courriel}))return res.status(409).json({message:"Courriel déjà utilisé"});const utilisateur=await Utilisateur.create({nom,courriel,motDePasse:await bcrypt.hash(motDePasse,12)});res.status(201).json({token:creerJeton(utilisateur),utilisateur:{id:utilisateur._id,nom:utilisateur.nom,courriel:utilisateur.courriel,role:utilisateur.role,restaurantId:utilisateur.restaurantId}});}
async function connexion(req,res){const courriel=String(req.body.courriel||"").trim().toLowerCase();const utilisateur=await Utilisateur.findOne({courriel}).select("+motDePasse");if(!utilisateur||!await bcrypt.compare(String(req.body.motDePasse||""),utilisateur.motDePasse))return res.status(401).json({message:"Identifiants invalides"});res.json({token:creerJeton(utilisateur),utilisateur:{id:utilisateur._id,nom:utilisateur.nom,courriel:utilisateur.courriel,role:utilisateur.role,restaurantId:utilisateur.restaurantId}});}
async function obtenirProfil(req,res){const utilisateur=await Utilisateur.findById(req.utilisateur.id);if(!utilisateur)return res.status(404).json({message:"Utilisateur introuvable"});res.json({utilisateur});}
async function modifierProfil(req,res){const champs={};["nom","telephone","adresses"].forEach(c=>{if(req.body[c]!==undefined)champs[c]=req.body[c]});if(req.body.courriel){const courriel=String(req.body.courriel).trim().toLowerCase();if(await Utilisateur.exists({courriel,_id:{$ne:req.utilisateur.id}}))return res.status(409).json({message:"Courriel déjà utilisé"});champs.courriel=courriel;}const utilisateur=await Utilisateur.findByIdAndUpdate(req.utilisateur.id,champs,{new:true,runValidators:true});res.json({utilisateur});}
async function motDePasseOublie(req,res){const courriel=String(req.body.courriel||"").trim().toLowerCase();const message="Si ce courriel est enregistré, un lien de réinitialisation a été envoyé";const utilisateur=await Utilisateur.findOne({courriel}).select("+jetonReinitialisation +expirationJetonReinitialisation");if(!utilisateur)return res.json({message});const jeton=crypto.randomBytes(32).toString("hex");utilisateur.jetonReinitialisation=crypto.createHash("sha256").update(jeton).digest("hex");utilisateur.expirationJetonReinitialisation=new Date(Date.now()+3600000);await utilisateur.save();res.json({message,jeton});}
async function reinitialiserMotDePasse(req,res){const jetonHache=crypto.createHash("sha256").update(String(req.body.jeton||"")).digest("hex");const utilisateur=await Utilisateur.findOne({courriel:String(req.body.courriel||"").toLowerCase(),jetonReinitialisation:jetonHache,expirationJetonReinitialisation:{$gt:new Date()}}).select("+motDePasse +jetonReinitialisation +expirationJetonReinitialisation");if(!utilisateur||String(req.body.nouveauMotDePasse||"").length<8)return res.status(400).json({message:"Jeton invalide, expiré ou mot de passe trop court"});utilisateur.motDePasse=await bcrypt.hash(req.body.nouveauMotDePasse,12);utilisateur.jetonReinitialisation=undefined;utilisateur.expirationJetonReinitialisation=undefined;await utilisateur.save();res.json({message:"Mot de passe réinitialisé"});}
module.exports={inscription,connexion,obtenirProfil,modifierProfil,motDePasseOublie,reinitialiserMotDePasse};
